<?php

namespace Nog\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRatingRepository extends EntityRepository
{
}
